/*
 * Copyright (c) 2026-present The MongoPlus Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.photowey.mongoplus.core.metadata;

import java.io.Serializable;

import io.github.photowey.mongoplus.core.util.Objects;
import io.github.photowey.mongoplus.core.util.Strings;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FieldMetadata - Describes a queryable field generated by APT.
 *
 * <p>The descriptor captures both Java-side and Mongo-side field identity so generated
 * {@code XxxColumns} classes can be used with wrapper APIs in a lambda-like style.</p>
 *
 * <h2>Usage Example</h2>
 * <pre>{@code
 * wrapper.eq(UserColumns.USER_NAME, "tom");
 * wrapper.orderByAsc(UserColumns.CREATED_AT);
 * updateWrapper.set(UserColumns.STATUS, 1);
 * }</pre>
 *
 * @param <T> the entity type
 * @author photowey
 * @version 2026.1.0.0
 * @see EntityMetadata
 * @since 2026/03/10
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FieldMetadata<T> implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;
    private String column;
    private String path;
    private Class<?> type;
    private Class<?> entityType;
    private FieldMetadata<?> parent;
    private boolean id;
    private boolean indexed;
    private boolean unique;

    /**
     * Resolve the Mongo query path for the field.
     *
     * @return the resolved Mongo path
     */
    public String resolvePath() {
        if (Strings.isNotBlank(this.path)) {
            return this.path;
        }
        if (Strings.isNotBlank(this.column)) {
            return this.column;
        }

        return Strings.defaultIfBlank(this.name, "");
    }

    /**
     * Resolve the Mongo column name for the field.
     *
     * @return the resolved Mongo column name
     */
    public String resolveColumn() {
        if (Strings.isNotBlank(this.column)) {
            return this.column;
        }
        if (Strings.isNotBlank(this.path)) {
            return this.path;
        }

        return Strings.defaultIfBlank(this.name, "");
    }

    /**
     * Determine whether this field is nested under another generated field descriptor.
     *
     * @return true if the field has a parent descriptor
     */
    public boolean isNested() {
        return Objects.nonNull(this.parent);
    }
}
