<?xml version="1.0" encoding="UTF-8" ?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.photowey</groupId>
        <artifactId>mongo-plus</artifactId>
        <version>${reversion}</version>
    </parent>

    <artifactId>mongo-plus-bom</artifactId>
    <name>mongo-plus-bom</name>
    <description>Bill of materials for aligning published MongoPlus module versions.</description>
    <packaging>pom</packaging>

    <modules>
    </modules>

    <properties>
    </properties>

    <dependencies>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-aggregation</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-annotation</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-apt</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-dsl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-executor</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-mapper</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-optimizer</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-plugin</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-query</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-spring-boot3-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.photowey</groupId>
                <artifactId>mongo-plus-wrapper</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
        </plugins>
    </build>

</project>
